### ISSUE TITLE
DllNotFoundException - Unable to load shared library 'libEmbeddedTerminal.so' or one of its dependencies

### ISSUE THREAD

**Issue by Clichas** [flathub/net.devolutions.RDM#23]
Hi, installed RDM 2023.2.2.6 today and im having this issue where everytime i open the preferences i get this error:

```
DllNotFoundException - Unable to load shared library 'libEmbeddedTerminal.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibEmbeddedTerminal.so: cannot open shared object file: No such file or directory

   at Services.Helpers.TerminalHelper.get_default_shell()
   at Devolutions.RemoteDesktopManager.Managers.FileManager.GetCommandPath(String commandName)
   at Services.Helpers.TerminalHelper.<>c.<GetAvailableTerminalEmulators>b__2_0(String emulator)
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at Services.Helpers.TerminalHelper.GetAvailableTerminalEmulators()
```

After the error only the tabs "General" and "User Interface" work, all the other tabs on preferences do nothing.

**Comment by tjone270** [comment]
Am also experiencing the same issue on RDM 2023.3.0.7 on Ubuntu 23.10.

**Comment by tjs-itb** [comment]
Hi, same issue - RDM 2023.3.0.8 on Linux Mint 21.2 Cinnamon / Cinnamon 5.8.4

**Comment by kkovaletp** [comment]
Hey, the same on my system as well.
Fedora KDE 39, however, I think that it doesn't matter and is reproducible on all supported systems.
Also, `flatpak update` returns next info, which means that RDM pack uses outdated platform and needs to be updated:

```
Info: org.gnome.Platform runtime branch 42 end of support due to:
The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: Applications using this runtime:
net.devolutions.RDM

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 21.08 end of support due to:
org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: Applications using this extension:
net.devolutions.RDM

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 end of support due to:
org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: Applications using this extension:
net.devolutions.RDM
```

Is this RDM pack maintained?
